CREATE TABLE agn_auxiliary_info
        (id TEXT, host_galaxy BIGINT, M_i DOUBLE PRECISION, seed BIGINT,
	tau_u DOUBLE PRECISION, tau_g DOUBLE PRECISION, tau_r DOUBLE PRECISION,
        tau_i DOUBLE PRECISION, tau_z DOUBLE PRECISION, tau_y DOUBLE PRECISION,
	sf_u DOUBLE PRECISION, sf_g DOUBLE PRECISION, sf_r DOUBLE PRECISION,
        sf_i DOUBLE PRECISION, sf_z DOUBLE PRECISION, sf_y DOUBLE PRECISION);
	
	
